[package]
name = "engine"
version.workspace = true
edition.workspace = true

[dependencies]
shared = { path = "../shared" }
bevy.workspace = true
bevy_rapier3d = { version = "0.36.0", default-features = false, features = ["dim3", "debug-render-3d"] }
mlua.workspace = true
rusqlite.workspace = true
rkyv.workspace = true
memmap2.workspace = true
color-eyre.workspace = true
crossbeam-channel.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_System_Threading"] }

[dev-dependencies]
tempfile = "3.20"
converter = { path = "../converter" }
ddsfile = "0.5"
ktx2.workspace = true
